//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOfJsonAndAjax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Department
    {
        public tbl_Department()
        {
            this.tbl_student = new HashSet<tbl_student>();
        }
    
        public int DepartmentId { get; set; }
        public string DeptName { get; set; }
    
        public virtual ICollection<tbl_student> tbl_student { get; set; }
    }
}
