//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOfJsonAndAjax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student
    {
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string MobNo { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual tbl_Department tbl_Department { get; set; }
    }
}
